// <auto-generated />
using System;
using LibraryDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryDB.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20201106104120_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("LibraryDB.Models.Books", b =>
                {
                    b.Property<long>("BookId")
                        .HasColumnName("BookID")
                        .HasColumnType("INT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<long>("GenId")
                        .HasColumnName("GenID")
                        .HasColumnType("INT");

                    b.Property<long>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("INT");

                    b.Property<DateTime>("PubYear")
                        .HasColumnType("DateTime");

                    b.HasKey("BookId");

                    b.HasIndex("GenId");

                    b.HasIndex("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryDB.Models.Employee", b =>
                {
                    b.Property<long>("EmpId")
                        .HasColumnName("EmpID")
                        .HasColumnType("INT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("CHAR(5)");

                    b.Property<long>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(11)");

                    b.HasKey("EmpId");

                    b.HasIndex("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("LibraryDB.Models.Genres", b =>
                {
                    b.Property<long>("GenId")
                        .HasColumnName("GenID")
                        .HasColumnType("INT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("GenTitle")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("GenId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("LibraryDB.Models.IssuedBooks", b =>
                {
                    b.Property<string>("ReturnMark")
                        .HasColumnType("CHAR (5)");

                    b.Property<long>("BookId")
                        .HasColumnName("BookID")
                        .HasColumnType("INT");

                    b.Property<long>("EmpId")
                        .HasColumnName("EmpID")
                        .HasColumnType("INT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("DateTime");

                    b.Property<long>("ReadId")
                        .HasColumnName("ReadID")
                        .HasColumnType("INT");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("DateTime");

                    b.HasKey("ReturnMark");

                    b.HasIndex("BookId");

                    b.HasIndex("EmpId");

                    b.HasIndex("ReadId");

                    b.ToTable("IssuedBooks");
                });

            modelBuilder.Entity("LibraryDB.Models.Positions", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("INT");

                    b.Property<string>("Demands")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Duties")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<double>("Salary")
                        .HasColumnType("FLOAT");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("LibraryDB.Models.Publicist", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("INT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PublicistTitle")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("Publicist");
                });

            modelBuilder.Entity("LibraryDB.Models.Readers", b =>
                {
                    b.Property<long>("ReadId")
                        .HasColumnName("ReadID")
                        .HasColumnType("INT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("CHAR(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PassportData")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(11)");

                    b.HasKey("ReadId");

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("LibraryDB.Models.Books", b =>
                {
                    b.HasOne("LibraryDB.Models.Genres", "Gen")
                        .WithMany("Books")
                        .HasForeignKey("GenId")
                        .IsRequired();

                    b.HasOne("LibraryDB.Models.Publicist", "IdNavigation")
                        .WithMany("Books")
                        .HasForeignKey("Id")
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryDB.Models.Employee", b =>
                {
                    b.HasOne("LibraryDB.Models.Positions", "IdNavigation")
                        .WithMany("Employee")
                        .HasForeignKey("Id")
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryDB.Models.IssuedBooks", b =>
                {
                    b.HasOne("LibraryDB.Models.Books", "Book")
                        .WithMany("IssuedBooks")
                        .HasForeignKey("BookId")
                        .IsRequired();

                    b.HasOne("LibraryDB.Models.Employee", "Emp")
                        .WithMany("IssuedBooks")
                        .HasForeignKey("EmpId")
                        .IsRequired();

                    b.HasOne("LibraryDB.Models.Readers", "Read")
                        .WithMany("IssuedBooks")
                        .HasForeignKey("ReadId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
